services:
  - type: web
    name: medisetu-backend
    env: docker
    rootDir: Medisetu/Backend
    plan: free
    autoDeploy: true

    envVars:
      - key: GROQ_API_KEY
        sync: false
